---
title: "Political Candidate Longevity"
author: "David Kane"
date: "4/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(primer.data)
library(rstanarm)
library(ggdist)
```


*What is the influence of age and gender on the expected longevity of political candidates?*

## Wisdom

Look at the data
Population
Ideal Preceptor Table
Representative
Validity

## Justice

$$y_i = \beta_0  + \beta_1 x_{1,i} + \beta_2 x_{2,i} + ... + \beta_n x_{n,i} + \epsilon_i$$


The above is our **data generating mechanism**, or DGM.

## Courage

### Model 1

$$lived\_after_i = \beta_0  + \beta_1 male_i + \beta_2 election\_age_i + \epsilon_i$$

```{r fit_1}
fit_1 <- stan_glm(data = governors,
                  formula = lived_after ~ sex + election_age,
                  refresh = 0,
                  seed = 12)
```

```{r fit_1_show}
fit_1
```

### Model 2


$$lived\_after_i = \beta_0  + \beta_1 male_i + \beta_2 election\_age_i + \beta_3 male_i election\_age_i + \epsilon_i$$

$$lived\_after_i = \beta_0  + \beta_2 election\_age_i +  \epsilon_i$$

```{r fit_2}
fit_2 <- stan_glm(data = governors,
                  formula = lived_after ~ sex + election_age + sex*election_age,
                  refresh = 0,
                  seed = 12)
```

```{r fit_2_show}
print(fit_2, details = FALSE)
```


## Temperance


```{r}
library(ggdist)

newobs <- tibble(sex = rep(c("Male", "Female"), 3), 
                 election_age = rep(c(30, 45, 60), 2),
                 names = paste(sex, election_age, sep = "_"))
```

```{r}
pe <- posterior_epred(fit_2,
                      newdata = newobs) %>% 
  as_tibble() %>% 
  set_names(newobs$names)
```

```{r}
x <- pe %>% 
  pivot_longer(names_to = "Group",
               values_to = "Years",
               cols = everything()) %>% 
  separate(Group, c("Gender", "Age"), "_") 
```

```{r}
x %>% 
  ggplot(aes(x = Years, y = Age, fill = Gender, alpha = 0.5)) +
  
  # position = "dodge" is the only sure way to see all 3 treatment distributions
  # identity, single, or any others drop "Sometimes" - topic for further study
  
    stat_slab() +
    guides(alpha = FALSE) +
    labs(title = "Candidate Longevity versus Gender and Age at Election",
         subtitle = "Age at election does not matter to longevity for female candidates . . . ?", 
         x = "Expected Years To Live Post Election",
         y = "Age at Election",
         caption = "Source: Barfort, Klemmensen & Larsen (2019)")
```


